### ISSUE TITLE
 BLE peripheral mode missing (Android Beacon)

### ISSUE THREAD

**Issue by voorstad** [CyanogenMod/android_device_motorola_peregrine#2]
For bluetooth syncing with another device (Polar V650), the bluetooth driver must be in a so called " BLE peripheral mode". According to this list, the Moto G XT1039 is capable in Android 5.1:

https://altbeacon.github.io/android-beacon-library/beacon-transmitter-devices.html

I found the following instructions for the Nexus 5, can this also be done for the Moto G?

> To make it work on newer android (>5.0) you should either recompile bt driver and adding a specific "#define" in the source code [1] or use a recompiled version of bluetooth drivers with peripheral mode activated [2] (for AOSP 5.0.1 or 5.1 and CM12 5.0.2 or 5.1.1) and [3] (for AOSP

https://code.google.com/p/android/issues/detail?id=79296

**Comment by luca020400** [comment]
http://review.cyanogenmod.org/#/c/146973/

**Comment by luca020400** [comment]
Download: https://googledrive.com/host/0B9vNfsTdldibZHBZNENXM3gtX28/bluetooth.default.so
Replace /system/lib/hw/bluetooth.default.so with the file you just downloaded
BLE peripheral mode should now work
Thanks.

**Comment by voorstad** [comment]
Hi Luca,

Thanks for your efforts. I have replaced the bluetooth.defaults.so and
rebooted the system. Unfortunately, it still does not work.

Other suggestions?

Thanks a million,
Eelco Mulder
Op 27 mei 2016 22:46 schreef "Luca Stefani" <notifications@github.com>:

**Comment by luca020400** [comment]
Could you take a logcat while you try to connect to the device?

**Comment by voorstad** [comment]
Hi Luca,

Hope this helps, see attachment.

Thank again!
Eelco
Op 27 mei 2016 23:54 schreef "Luca Stefani" <notifications@github.com>:

> Could you take a logcat while you try to connect to the device?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CyanogenMod/android_device_motorola_peregrine/issues/2#issuecomment-222261705>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AB3TtE__CWVl-ODXIHsLsxGFVZIQ8aRZks5qF2gQgaJpZM4Ioe0X>
> .
>

05-27 23:46:19.508 W/PackageManager(816): Unknown permission com.google.android.gallery3d.permission.GALLERY_PROVIDER in package com.android.bluetooth
05-27 23:46:25.259 I/ActivityManager(816): Start proc 1457:com.skype.raider/u0a81 for broadcast com.skype.raider/com.skype.android.audio.BluetoothReceiver
05-27 23:46:46.316 I/ActivityManager(816): Start proc 2695:com.android.bluetooth/1002 for on-hold
05-27 23:46:47.903 W/PackageManager(816): Unknown permission android.permission.MMS_PUSH in package org.codeaurora.bluetooth
05-27 23:46:48.061 W/PackageManager(816): Unknown permission com.google.android.gallery3d.permission.GALLERY_PROVIDER in package com.android.bluetooth
05-27 23:46:50.007 I/Telecom (816): BluetoothPhoneService: queryPhoneState
05-27 23:46:50.022 I/Telecom (816): BluetoothPhoneService: updateHeadsetWithCallState numActive 0, numHeld 0, callState 6, ringing number [da39a3ee5e6b4b0d3255bfef95601890afd80709], ringing type 128
05-27 23:46:50.182 I/ActivityManager(816): Start proc 3136:com.strava/u0a93 for broadcast com.strava/.sensors.BluetoothChangeReceiver
05-27 23:46:50.506 I/Telecom (816): BluetoothPhoneService: queryPhoneState
05-27 23:46:50.507 I/Telecom (816): BluetoothPhoneService: updateHeadsetWithCallState numActive 0, numHeld 0, callState 6, ringing number [da39a3ee5e6b4b0d3255bfef95601890afd80709], ringing type 128
05-27 23:46:52.392 I/ActivityManager(816): Start proc 3374:com.skype.raider/u0a81 for broadcast com.skype.raider/com.skype.android.audio.BluetoothReceiver
05-27 23:46:54.740 I/ActivityManager(816): Start proc 3606:vc.core/u0a98 for broadcast vc.core/somo.android.sensor.BluetoothDeviceReceiver
05-27 23:46:59.418 I/ActivityManager(816): Start proc 4072:com.spotify.music/u0a91 for broadcast com.spotify.music/com.spotify.mobile.android.service.BluetoothServiceManager
05-27 23:47:00.494 I/ActivityManager(816): START u0 {act=android.settings.BLUETOOTH_SETTINGS flg=0x14000000 cmp=com.android.settings/.Settings$BluetoothSettingsActivity} from uid 10018 on display 0
05-27 23:47:03.196 W/ContextImpl(1098): Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1231 android.content.ContextWrapper.startService:587 android.content.ContextWrapper.startService:587 com.android.settings.bluetooth.DockEventReceiver.beginStartingService:134 com.android.settings.bluetooth.DockEventReceiver.onReceive:115 
05-27 23:47:19.573 I/ActivityManager(816): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.kyriakosalexandrou.bluetoothsupportcheck/.MainActivity (has extras)} from uid 10020 on display 0
05-27 23:47:19.696 I/ActivityManager(816): Start proc 6452:com.kyriakosalexandrou.bluetoothsupportcheck/u0a32 for activity com.kyriakosalexandrou.bluetoothsupportcheck/.MainActivity
05-27 23:47:21.408 I/WindowManager(816): Screenshot max retries 4 of Token{9247a28 ActivityRecord{ae6904b u0 com.kyriakosalexandrou.bluetoothsupportcheck/.MainActivity t985}} appWin=Window{c1a102b u0 com.kyriakosalexandrou.bluetoothsupportcheck/com.kyriakosalexandrou.bluetoothsupportcheck.MainActivity} drawState=4
05-27 23:47:28.897 W/WindowManager(816): Force clearing freeze: AppWindowToken{d0be627 token=Token{9247a28 ActivityRecord{ae6904b u0 com.kyriakosalexandrou.bluetoothsupportcheck/.MainActivity t985}}}
05-27 23:47:28.898 I/WindowManager(816): Screen frozen for +2s40ms due to AppWindowToken{d0be627 token=Token{9247a28 ActivityRecord{ae6904b u0 com.kyriakosalexandrou.bluetoothsupportcheck/.MainActivity t985}}}
05-27 23:47:59.461 I/ActivityManager(816): START u0 {act=android.bluetooth.adapter.action.REQUEST_ENABLE cmp=com.android.settings/.bluetooth.RequestPermissionActivity} from uid 10110 on display 0
05-27 23:48:01.352 I/ActivityManager(816): START u0 {act=android.bluetooth.adapter.action.REQUEST_ENABLE cmp=com.android.settings/.bluetooth.RequestPermissionActivity} from uid 10110 on display 0
05-27 23:48:56.286 I/ActivityManager(816): Start proc 18196:com.skype.raider/u0a81 for broadcast com.skype.raider/com.skype.android.audio.BluetoothReceiver
05-27 23:49:00.494 I/ActivityManager(816): Start proc 18466:com.spotify.music/u0a91 for broadcast com.spotify.music/com.spotify.mobile.android.service.BluetoothServiceManager
05-27 23:49:17.408 I/ActivityManager(816): Waited long enough for: ServiceRecord{fffc811 u0 com.spotify.music/com.spotify.mobile.android.spotlets.appprotocol.service.AppProtocolBluetoothService}
05-27 23:49:54.595 I/WindowState(816): WIN DEATH: Window{ead6496 u0 com.android.settings/com.android.settings.Settings$BluetoothSettingsActivity}
05-28 00:11:40.835 I/WindowState(816): WIN DEATH: Window{b593d05 u0 com.kyriakosalexandrou.bluetoothsupportcheck/com.kyriakosalexandrou.bluetoothsupportcheck.MainActivity}
05-28 00:11:40.989 I/ActivityManager(816): Process com.kyriakosalexandrou.bluetoothsupportcheck (pid 6452) has died
05-28 00:11:44.315 I/ActivityManager(816):   psvc  SB    3053 kB: com.android.bluetooth (pid 2695) service
05-28 00:11:44.315 I/ActivityManager(816):                        com.android.bluetooth/.hfp.HeadsetService<=Proc{1120:com.android.systemui/u0a18}
05-28 00:14:49.307 D/BluetoothManagerService(816): Message: 20
05-28 00:14:49.307 D/BluetoothManagerService(816): Added callback: android.bluetooth.IBluetoothManagerCallback$Stub$Proxy@3710646:true
05-28 00:14:49.356 D/BluetoothGattServer(4302): registerCallback()
05-28 00:14:49.362 D/BluetoothGattServer(4302): registerCallback() - UUID=f229f29e-2806-49b5-b195-77f0532af295
05-28 00:14:49.366 D/BluetoothGattServer(4302): onServerRegistered() - status=0 serverIf=5
05-28 00:14:49.367 D/BluetoothGattServer(4302): addService() - service: fb005c14-9815-d766-a528-32d54cf35530
05-28 00:14:49.377 D/BluetoothGattServer(4302): onServiceAdded() - service=fb005c14-9815-d766-a528-32d54cf35530status=0
05-28 00:30:46.957 W/AudioManagerAndroid(11194): Requires BLUETOOTH permission
05-28 00:30:51.449 I/ActivityManager(816):   psvc  SB    5102 kB: com.android.bluetooth (pid 2695) service
05-28 00:30:51.449 I/ActivityManager(816):                        com.android.bluetooth/.hfp.HeadsetService<=Proc{1120:com.android.systemui/u0a18}
05-28 00:31:46.175 W/AudioManagerAndroid(31017): Requires BLUETOOTH permission
05-28 00:31:47.652 D/BluetoothManagerService(816): Message: 20
05-28 00:31:47.653 D/BluetoothManagerService(816): Added callback: android.bluetooth.IBluetoothManagerCallback$Stub$Proxy@fe2a0f0:true
05-28 00:32:14.609 W/AudioManagerAndroid(12534): Requires BLUETOOTH permission
05-28 00:33:38.090 D/BluetoothManagerService(816): Message: 20
05-28 00:33:38.090 D/BluetoothManagerService(816): Added callback: android.bluetooth.IBluetoothManagerCallback$Stub$Proxy@2cba20d:true
05-28 00:33:38.122 D/BluetoothGattServer(13569): registerCallback()
05-28 00:33:38.125 D/BluetoothGattServer(13569): registerCallback() - UUID=3183dba8-ad38-47a2-bf05-1968643d757c
05-28 00:33:38.136 D/BluetoothGattServer(13569): onServerRegistered() - status=0 serverIf=5
05-28 00:33:38.137 D/BluetoothGattServer(13569): addService() - service: fb005c14-9815-d766-a528-32d54cf35530
05-28 00:33:38.148 D/BluetoothGattServer(13569): onServiceAdded() - service=fb005c14-9815-d766-a528-32d54cf35530status=0
05-28 00:33:43.865 I/ActivityManager(816): Start proc 13633:com.android.settings/1000 for activity com.android.settings/.Settings$BluetoothSettingsActivity
05-28 00:33:44.251 D/BluetoothManagerService(816): Message: 20
05-28 00:33:44.251 D/BluetoothManagerService(816): Added callback: android.bluetooth.IBluetoothManagerCallback$Stub$Proxy@b7888e9:true
05-28 00:33:44.275 D/LocalBluetoothProfileManager(13633): Adding local A2DP SRC profile
05-28 00:33:44.278 D/BluetoothManagerService(816): Message: 30
05-28 00:33:44.281 D/LocalBluetoothProfileManager(13633): Adding local HEADSET profile
05-28 00:33:44.284 D/BluetoothManagerService(816): Message: 30
05-28 00:33:44.289 D/BluetoothManagerService(816): Message: 30
05-28 00:33:44.295 D/BluetoothManagerService(816): Message: 30
05-28 00:33:44.298 D/LocalBluetoothProfileManager(13633): Adding local MAP profile
05-28 00:33:44.301 D/BluetoothMap(13633): Create BluetoothMap proxy object
05-28 00:33:44.302 D/BluetoothManagerService(816): Message: 30
05-28 00:33:44.306 D/BluetoothDun(13633): BluetoothDun() call bindService
05-28 00:33:44.306 D/BluetoothManagerService(816): Message: 30
05-28 00:33:44.312 D/BluetoothManagerService(816): Message: 30
05-28 00:33:44.313 D/LocalBluetoothProfileManager(13633): LocalBluetoothProfileManager construction complete
05-28 00:33:44.670 D/A2dpService(2695): getA2DPService(): returning com.android.bluetooth.a2dp.A2dpService@101273a
05-28 00:33:44.671 I/BluetoothAdapterService(2695): setScanMode: prev mode: 21 new mode: 23
05-28 00:33:44.688 D/BluetoothAdapterProperties(2695): Discoverable Timeout:120
05-28 00:33:44.690 D/BluetoothAdapterProperties(2695): Scan Mode:23
05-28 00:33:44.701 D/LocalBluetoothManager(13633): setting foreground activity to non-null context
05-28 00:33:44.754 D/A2dpService(2695): getA2DPService(): returning com.android.bluetooth.a2dp.A2dpService@101273a
05-28 00:33:44.761 D/A2dpService(2695): getA2DPService(): returning com.android.bluetooth.a2dp.A2dpService@101273a
05-28 00:33:44.762 I/BluetoothAdapterService(2695): setScanMode: prev mode: 23 new mode: 23
05-28 00:33:44.766 D/BluetoothAdapterProperties(2695): Discoverable Timeout:120
05-28 00:33:44.767 D/BluetoothAdapterProperties(2695): Scan Mode:23
05-28 00:33:44.845 D/BluetoothA2dp(13633): Proxy object connected
05-28 00:33:44.848 D/BluetoothHeadset(13633): Proxy object connected
05-28 00:33:44.848 D/HeadsetProfile(13633): Bluetooth service connected
05-28 00:33:44.849 D/BluetoothHeadset(13633): getConnectedDevices()
05-28 00:33:44.857 D/BluetoothInputDevice(13633): Proxy object connected
05-28 00:33:44.857 D/HidProfile(13633): Bluetooth service connected
05-28 00:33:44.869 D/BluetoothPan(13633): BluetoothPAN Proxy object connected
05-28 00:33:44.870 D/PanProfile(13633): Bluetooth service connected
05-28 00:33:44.870 D/BluetoothMap(13633): Proxy object connected
05-28 00:33:44.870 D/MapProfile(13633): Bluetooth service connected
05-28 00:33:44.870 D/BluetoothMap(13633): getConnectedDevices()
05-28 00:33:44.876 D/DunServerProfile(13633): Bluetooth service connected
05-28 00:33:44.876 D/BluetoothPbap(13633): Proxy object connected
05-28 00:33:44.876 D/PbapServerProfile(13633): Bluetooth service connected
05-28 00:33:44.949 V/BluetoothDiscoveryReceiver(13633): Received: android.bluetooth.adapter.action.DISCOVERY_STARTED
05-28 00:33:45.257 I/ActivityManager(816): Displayed com.android.settings/.Settings$BluetoothSettingsActivity: +1s425ms
05-28 00:33:52.252 D/LocalBluetoothManager(13633): setting foreground activity to null
05-28 00:33:52.259 D/A2dpService(2695): getA2DPService(): returning com.android.bluetooth.a2dp.A2dpService@101273a
05-28 00:33:52.261 I/BluetoothAdapterService(2695): setScanMode: prev mode: 23 new mode: 21
05-28 00:33:52.262 D/BluetoothAdapterProperties(2695): Discoverable Timeout:120
05-28 00:33:52.263 D/BluetoothAdapterProperties(2695): Scan Mode:21
05-28 00:33:52.279 V/BluetoothDiscoveryReceiver(13633): Received: android.bluetooth.adapter.action.DISCOVERY_FINISHED
05-28 00:34:41.921 D/BluetoothMapAppObserver(2695): onReceive
05-28 00:34:41.922 D/BluetoothMapAppObserver(2695): The installed package is: com.nolanlawson.logcat
05-28 00:34:41.941 D/BluetoothMapAppObserver(2695): Found 0 application(s) with intent android.bluetooth.action.BLUETOOTH_MAP_PROVIDER
05-28 00:34:41.942 D/BluetoothMapAppObserver(2695): Found 0 application(s) with intent android.bluetooth.action.BLUETOOTH_MAP_IM_PROVIDER
05-28 00:34:53.453 D/BluetoothManagerService(816): Message: 20
05-28 00:34:53.453 D/BluetoothManagerService(816): Added callback: android.bluetooth.IBluetoothManagerCallback$Stub$Proxy@2a1dd36:true
05-28 00:35:09.210 I/SwapManager(14645): Asked to stop swapping, will stop bluetooth, wifi, and move service to BG for GC.
05-28 00:39:29.310 I/ActivityManager(816): START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.kyriakosalexandrou.bluetoothsupportcheck/.MainActivity bnds=[184,386][360,588] (has extras)} from uid 10020 on display 0
05-28 00:39:29.369 I/ActivityManager(816): Start proc 16245:com.kyriakosalexandrou.bluetoothsupportcheck/u0a32 for activity com.kyriakosalexandrou.bluetoothsupportcheck/.MainActivity
05-28 00:39:29.498 W/System  (16245): ClassLoader referenced unknown path: /data/app/com.kyriakosalexandrou.bluetoothsupportcheck-1/lib/arm
05-28 00:39:29.711 D/BluetoothManagerService(816): Message: 20
05-28 00:39:29.711 D/BluetoothManagerService(816): Added callback: android.bluetooth.IBluetoothManagerCallback$Stub$Proxy@9c4d64c:true
05-28 00:39:29.921 I/ActivityManager(816): Displayed com.kyriakosalexandrou.bluetoothsupportcheck/.MainActivity: +579ms
05-28 00:40:14.242 W/AudioManagerAndroid(16523): Requires BLUETOOTH permission

**Comment by voorstad** [comment]
Hi Luca,

Have the logs been helpful? If you need anything else, please just let me
know and I will try to provide you....

Thanks again!
Eelco Mulder

2016-05-28 0:43 GMT+02:00 Eelco Mulder <oclee.redlum@gmail.com>:
